functional tests: Fix wheel errors when provisioning VM
> error: invalid command 'bdist_wheel'

Kept popping up in the logs. It seems like `wheel` isn't in the deps of
the installed python packages. Therefore we now install it ourselves.

freedombox/plinth#1521 - Provision VM to run function functional tests

Reviewed-by: James Valleroy <jvalleroy@mailbox.org>