pyproject: Ignore missing types for numpy (needed by pytest)
- Otherwise, on Debian stable, running make check-type results in following
error:

/usr/lib/python3/dist-packages/_pytest/python_api.py:24: error: Cannot find
implementation or library stub for module named "numpy"  [import]

Signed-off-by: Sunil Mohan Adapa <sunil@medhas.org>
Reviewed-by: James Valleroy <jvalleroy@mailbox.org>